### ISSUE TITLE
Improve Text Tooling

### ISSUE THREAD

**Issue by quasado** [Gravit-io/gravit#237]
1. Make Text behave like a Rectangle considering transformed resizing
2. Always use the distance between points for calculating the text-box the text aligns within and not use the geometry bbox for that
3. The transform box should always transform the text's box and _not_ the text itself
4. Double Click on bottom handle toggles auto-height on/off
5. Double Click on right handle toggles auto-width on/off
6. Add some handling to paint handles with white fill/selection color as border when text is auto-height / auto-width on either the bottom-handle and / or the right-center handle
7. When resizing with the right-center handle, auto-height should *not* be turned off
8. When resizing with the bottom-center handle, auto-width should *not* be turned off

**Comment by anna-ignatenkova** [comment]
3. If skew or rotation is applied via transform box, how this may transform text's box without transforming the text itself?
May be to use resize handles of text box for transforming the box only, but when the transformation is made via transform box or transform panel, then to apply this transformation to the text also? Or otherwise we will need a different behavior for resize, rotate, and skew transformations when transforming via transform box.

**Comment by anderswelt** [comment]
3. Maybe this a slight missunderstanding -- it should of course transform the text (aka the outputted text vectors). I was actually talking about the scale handles of the transformbox -- they're currently scaling the text whereas they should instead resize the text's box.

**Comment by anna-ignatenkova** [comment]
Hmm... I still don't have a clear understanding. This means that we should handle differently resizing of transform box via scale handles of the transformbox, and rotation. As rotation should rotate the text, but resizing should resize only the text box. Right? Or do you mean resizing via the handles of text box (blue), and not the transform box (black)?

**Comment by anderswelt** [comment]
Hmm ok you're right. Let's remove point #3 for now until I've figured a final solution. Resizing via the handles of text box (blue) should of course as stated behave like the one from rectangle and resize the text's box
