### ISSUE TITLE
Portable mode (feature request)

### ISSUE THREAD

**Issue by rolandtoth** [Gravit-io/gravit#245]
(Windows only)
Is there any way to force Gravit to save settings to its own directory?
Other webkit-based applications (eg. Toggl) accept "--user-data-dir=Path\To\MyDir" switch but Gravit seems not.

If there is none, any chance to have such feature?

**Comment by anderswelt** [comment]
It should work as we didn't change anything to that. Anyway the final release will be browser-based only including offline functionality so this shouldn't be an issue anymore
